# 버전 - 명시하지 않아도 인식가능
version: '3'

# 서비스 정의
services:
## 서비스명
  db:
	 # platform : linux/arm64
  ## 컨테이너명
    container_name: db-server
  ## 사용 이미지
    image: mysql:latest
  ## 호스트-컨테이너 매핑 포트
    ports:
      - 3306:3306    
    volumes:
      - /home/ubuntu/data/mysql:/var/lib/mysql
  ## 환경변수, -e
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secerts.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secerts.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secerts.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secerts.MYSQL_PASSWORD }}
  ## 네트워크
    networks:
      - app-network
  ## 연결 상태 확인
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100
## 서비스명
  backend:
    container_name: backend-server
    ## 빌드 명령
    build:
    ## 작업위치
      context: .
    ## Dockerfile 경로
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    ## 의존서비스 - db(서비스명)가 실행되어야지만 backend 서비스 가능
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

## 네트워크
networks:
  app-network:
    driver: bridge
